#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "System Recovery" --class recovery {
    rmmod tpm
    echo    'Loading Linux 6.1.0-13-amd64'
    search --no-floppy --fs-uuid --set=root 4844C53444C52592
    set isofile="/Bootable/debian-live-12.2.0-amd64-mate.iso"
    loopback loop $isofile
    linux (loop)/live/vmlinuz boot=live findiso=$isofile noeject quiet loglevel=0 profile fsck.mode=skip
    echo    'Loading initial ramdisk ...'
    initrd (loop)/live/initrd.img
}